// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElForm: typeof import('element-plus/es')['ElForm']
  const ElFormItem: typeof import('element-plus/es')['ElFormItem']
  const ElIcon: typeof import('element-plus/es')['ElIcon']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElOption: typeof import('element-plus/es')['ElOption']
  const ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
  const ElSelect: typeof import('element-plus/es')['ElSelect']
  const ElTabPane: typeof import('element-plus/es')['ElTabPane']
  const ElTabs: typeof import('element-plus/es')['ElTabs']
}
export {}
